### Register User

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Vinuka",
  "email": "vinuka999@gmail.com",
  "password": "123456"
}



### Login User

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "vinuka9999@gmail.com",
  "password": "123456"
}


### Get Current User

GET http://localhost:5000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYzNiYmFkODc4N2Q1NTY0MmVhMDU0YyIsImlhdCI6MTc5MTI1MTcwMiwiZXhwIjoxNzkzODQzNzAyfQ.8rONj-sVArhuDgnn5WVzs8G673eudE8dG9hVSwfdKD0



### Create Tournament

POST http://localhost:5000/api/tournaments
Content-Type: application/json

{
  "title": "Legends Clash",
  "game": "League of Legends",
  "description": "Competitive League of Legends championship.",
  "date": "2026-12-05",
  "price": 1800,
  "totalSeats": 200,
  "image": ""
}


### Get All Tournaments

GET http://localhost:5000/api/tournaments


### Reserve Tournament Ticket

POST http://localhost:5000/api/tickets/reserve/6ac71de4c9b9825aad7c2be9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYzNiYmFkODc4N2Q1NTY0MmVhMDU0YyIsImlhdCI6MTc5MTUxNTg4MSwiZXhwIjoxNzk0MTA3ODgxfQ.2H9E1kEGQQTuwfHmnbn7sqqksdZGsjFmTgYBiruqgK4
Content-Type: application/json


### Get My Tickets

GET http://localhost:5000/api/tickets/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYzNiYmFkODc4N2Q1NTY0MmVhMDU0YyIsImlhdCI6MTc5MTUxNTg4MSwiZXhwIjoxNzk0MTA3ODgxfQ.2H9E1kEGQQTuwfHmnbn7sqqksdZGsjFmTgYBiruqgK4


### Cancel Ticket

PATCH http://localhost:5000/api/tickets/cancel/6ac85d46a752ea7a732a73ee
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhYzNiYmFkODc4N2Q1NTY0MmVhMDU0YyIsImlhdCI6MTc5MTYzMzc1NSwiZXhwIjoxNzk0MjI1NzU1fQ.A1qFQukBx6Sp6WhTpbFp9Aw3oCfLSjVwJs_1LPzSOSk
Content-Type: application/json



### Get Leaderboard

GET http://localhost:5000/api/leaderboard